rails/app/config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :stories
  root "home#index"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destory"
  get "/about", to: "home#about"
  get  "/signup", to: "users#new"
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails/app/app/controllers/stories_controller.rb
class StoriesController < ApplicationController


before_action :set_story, only: [:edit, :update, :show, :destroy]
before_action :require_user, except: [:index, :show]
before_action :require_same_user, only: [:edit, :update, :destroy]


 def new
  @storie = Storie.new
 end

 def index
  @storie = Storie.paginate(page: params[:page], per_page: 3)
 end
 

 def destroy 
  @storie = Storie.find(params[:id])
  @storie.destroy
  flash[:danger] = "Story was successfully deleted"
  redirect_to stories_path
 end

 def edit
  @storie = Storie.find(params[:id])
 end

 def update
  @storie = Storie.find(params[:id])
  if @storie.update(storie_params)
   flash[:success] = "Story was successfully updated"
   redirect_to @storie
  else
   render 'edit'
  end
 end

 def create
  
  @storie = Storie.new(storie_params)
  @storie.user = current_user  
  if @storie.save
    flash[:success] = "Story was successfully created"
    redirect_to @storie
  else
    render 'new'
  end
 
 end

 def show
  @storie = Storie.find(params[:id])
 end


 private
  def storie_params
   params.require(:storie).permit(:name, :content, category_ids: [])
  end 

  def set_story
  @storie = Storie.find(params[:id])
  end

  def require_same_user
   if current_user != @storie.user and !current_user.admin?
   flash[:danger] = "You can only edit your own articles"
   redirect_to root_path
   end
  end

end

rails/app/app/views/stories/_form.html.erb
<%= form_with(model: @storie,html: {class: "form-horizontal", role: "form"}, local: true) do |form| %>
   <% if @storie.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@storie.errors.count, "error") %> prohibited
        this storie from being saved:
      </h2>
      <ul>
        <% @storie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class='row'>
<div class='col-sm-12'>

<div class = "form-group">
<div class = "control-label col-sm-2">
<%= form.label :name %>
</div>
<div class="col-sm-8">
<%= form.text_field :name, class: "form-control", placeholder: "Name of the story", autofocus:true %>
</div>
</div>
  
<div class = "form-group">
<div class = "control-label col-sm-2">

    <%= form.label :content %>
</div>
<div class="col-sm-8">  
    <%= form.text_area :content, rows: 10, class: "form-control", placeholder: "Content of the story" %>
  </div>
</div>

 <div class = "form-group">
<div class="col-sm-offset-2 col-sm-10">  
  <%= form.submit class: 'btn-primary btn-lg' %>
  </div>
</div>

<% end %>


<div class="col-xs-4 col-xs-offset-4">
[ <%= link_to "Cancel request and return to stories listing", stories_path %> ]
</div>
</div>
</div>

rails/app/app/views/stories/_storie.html.erb
<% obj.each do |storie| %>
<div class="row">
<div class="col-sm-12 col-xs-offset-2">
<div class="card text-white bg-secondary mb-3">
<div class="card-header text-white bg-dark">

<h5><%= link_to storie.name,story_path(storie) %></h5>

</div>
<div class="storie.body">
<br>
<h6><%= truncate(storie.content, length: 50) %></h6>
<small>Created by: <%= storie.user.username if storie.user%>,
<%= time_ago_in_words(storie.created_at) %> ago</small>
<br><br>
<% if storie.categories.any? %>
<p>Categories: <%= render storie.categories %></p>
<% end %>


</div>
<% if logged_in? && (current_user == storie.user || current_user.admin?) %>
<div class="card-footer bg-transparent border-success">
<div class="storie-actions">

<%= link_to "Edit this story", edit_story_path(storie), class: "btn btn-xs btn-primary" %>
<%= link_to "Delete this Story", story_path(storie), method: :delete,
data: { confirm: "Are you sure you want to delete the story?"},
class: "btn btn-xs btn-danger" %>
</div>
</div>

<% end %>

</div>
</div>
</div>
<br>
<% end %>

rails/app/app/views/stories/edit.html.erb
<h1> Edit Existing Story </h1>
<%= render 'form' %>

rails/app/app/views/stories/index.html.erb
<h3> Listing All Stories </h3>
<br>
<%= link_to "Create a story", new_story_path, class: "btn btn-xs btn-success" %> | 
<%= link_to "View All Writers", users_path, class: "btn btn-xs btn-primary" %> | 
<% if logged_in? %>
<%= link_to "Go to your Profile", user_path(current_user), class: "btn btn-xs btn-primary" %>
<% end %>
<br>
<br>
<%= render 'storie', obj: @storie %>
<div class="d-flex justify-content-center">
<%= will_paginate(@storie, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

rails/app/app/views/stories/new.html.erb

<br>
<h2>  Create a Story</h2>
<%= render 'form' %>

rails/app/app/views/stories/show.html.erb
<h1 align="center"> Story Name: <%= @storie.name %></h1>
<br>

<div class="card text-white bg-secondary mb-3">
<h6><strong>Content:</strong></h6>
<br>
 <%=  simple_format(@storie.content) %>
<br>

<% if @storie.categories.any? %>
<p>Categories: <%= render @storie.categories %></p>
<% end %>

<br>
 <div class="card-footer bg-transparent border-success">
<div class="storie-actions">
<%= link_to "Back to all stories", stories_path, class: "btn btn-xs btn-success" %>
<% if logged_in? && (current_user == @storie.user || current_user.admin? ) %> 
<%= link_to "Edit this story", edit_story_path(@storie), class: "btn btn-xs btn-primary" %>
<%= link_to "Delete this Story", story_path(@storie), method: :delete, 
data: { confirm: "Are you sure you want to delete the story?"}, 
class: "btn btn-xs btn-danger" %>
<% end %>
</div>
</div>
</div>