rails/app/config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :stories
  root "home#index"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destory"
  get "/about", to: "home#about"
  get  "/signup", to: "users#new"
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails/app/app/models/category.rb
class Category < ApplicationRecord
has_many :storie_categories
has_many :storie, through: :storie_categories
validates :name, presence: true, length: { minimum: 3, maximum: 25 }
validates_uniqueness_of :name
end

rails/app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

before_action :require_admin, except: [:index, :show]

def index
@category = Category.paginate(page: params[:page], per_page: 5)
end

def new
@category = Category.new
end

def create
@category = Category.new(category_params)
if @category.save
flash[:success] = "Category was created successfully"
redirect_to categories_path
else
render 'new'
end
end



def edit
@category = Category.find(params[:id])
end
def update
@category = Category.find(params[:id])
if @category.update(category_params)
flash[:success] = "Category name was successfully updated"
redirect_to category_path(@category)
else
render 'edit'
end
end



def show
@category = Category.find(params[:id])
@category_storie = @category.storie.paginate(page: params[:page], per_page: 3)
end

private

def category_params
params.require(:category).permit(:name)
end


def require_admin
if !logged_in? || (logged_in? and !current_user.admin? )
flash[:danger] = "Only Admins can perform this action"
redirect_to categories_path
end
end


end

rails/app/app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name,category_path(category) %> &nbsp;</span>

rails/app/app/views/categories/edit.html.erb
<h1>Edit category</h1>

<%= form_with(model: @category,html: {class: "form-horizontal", role: "form"}, local: true) do |form| %>
   <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being created:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class='row'>
<div class='col-sm-12'>

<div class = "form-group">
<div class = "control-label col-sm-2">
<%= form.label :name %>
</div>
<div class="col-sm-8">
<%= form.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus:true %>
</div>
</div>
  

 <div class = "form-group">
<div class="col-sm-offset-2 col-sm-10">  
  <%= form.submit class: 'btn-primary btn-lg' %>
  </div>
</div>
<% end %>


<div class="col-xs-4 col-xs-offset-4">
[ <%= link_to "Cancel request and return to stories listing", stories_path %> ]
</div>
</div>
</div>

rails/app/app/views/categories/index.html.erb
<h3>Listing all Categories</h3>
<hr>
<% @category.each do |category| %>

<div class="row">
<div class="col-sm-12 col-xs-offset-2">
<div class="card bg-light mb-3 border-dark mb-3">

<h3><%= link_to category.name,category_path(category) %></h3>
<br>
<small><%= pluralize(category.storie.count, "story") %></small>
</div>
</div>
</div>
<br>
<% end %>
<div class="d-flex justify-content-center">
<%= will_paginate(@category, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

rails/app/app/views/categories/new.html.erb
<h1>Create a new category</h1>

<%= form_with(model: @category,html: {class: "form-horizontal", role: "form"}, local: true) do |form| %>
   <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being created:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class='row'>
<div class='col-sm-12'>

<div class = "form-group">
<div class = "control-label col-sm-2">
<%= form.label :name %>
</div>
<div class="col-sm-8">
<%= form.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus:true %>
</div>
</div>
  

 <div class = "form-group">
<div class="col-sm-offset-2 col-sm-10">  
  <%= form.submit class: 'btn-primary btn-lg' %>
  </div>
</div>
<% end %>


<div class="col-xs-4 col-xs-offset-4">
[ <%= link_to "Cancel request and return to stories listing", stories_path %> ]
</div>
</div>
</div>

rails/app/app/views/categories/show.html.erb
<h3><%= "Category: " + @category.name %> </h3>

<% if logged_in? and current_user.admin? %>

<span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
<br>
<% end %>

<br>
<%= link_to "View all categories", categories_path, class: "btn btn-xs btn-success" %> |
<%= link_to "Create a story", new_story_path, class: "btn btn-xs btn-success" %> | 
<%= link_to "View All Writers", users_path, class: "btn btn-xs btn-primary" %> | 
<% if logged_in? %>
<%= link_to "Go to your Profile", user_path(current_user), class: "btn btn-xs btn-primary" %>
<% end %>
<br>
<br>
<%= render 'stories/storie', obj: @category_storie %>
<div class="d-flex justify-content-center">
<%= will_paginate(@category_storie, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>