rails/app/config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :stories
  root "home#index"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destory"
  get "/about", to: "home#about"
  get  "/signup", to: "users#new"
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails/app/app/views/layouts/_footer.html.erb
<div class="container">
<footer class="footer">
<small>
@Copyright Sid Stories
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
</ul>
</nav>
</footer>
</div>

rails/app/app/views/layouts/_messages.html.erb
<div class="row">
<div class="col-sm-10 col-xs-offset-1">
<% flash.each do |name, msg| %>
<div class='alert alert-<%="#{name}" %>'>
<a href="#" class="close" data-dismiss="alert">×</a>
<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
</div>
<% end %>
</div>
</div>

rails/app/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
<%= link_to "SidStories", root_path, class:"navbar-brand", id: "brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

 <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li><%= link_to "Stories", stories_path %></li>
 <li><%= link_to "Users", users_path %></li>



<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>


        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
   
 <a class="dropdown-item"><%= link_to "All Categories", categories_path %></a>


<% Category.all.each do |category| %>
<a class="dropdown-item"><%= link_to category.name, category_path(category) %></a>
<% end %>

<% if logged_in? and current_user.admin? %>

<div class="dropdown-divider"></div>
          <a class="dropdown-item"><%= link_to "Create new Category", new_category_path %></a>
        </div>

<% end %>
 
 </div>
      </li>




<% if logged_in? %>

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>


        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item"><%= link_to "New Story", new_story_path %></a>
 
 </div>
      </li>
<% end %>

</ul>

<ul class="nav navbar-nav navbar-right my-2">

<% if logged_in? %>

<li><%= link_to "Logout", logout_path, method: :delete %></li>


<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Your Profile <%= "Admin" if current_user.admin? %>
        </a>


        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

      <a class="dropdown-item"><%= link_to "Edit profile", edit_user_path(current_user) %></a>
      <a class="dropdown-item"> <%= link_to "View profile", user_path(current_user) %></a>
             
  </div>
      </li>




<% else %>
<li><%= link_to "Login", login_path %></li>
<br>
<li><%= link_to "Signup", signup_path %></li>
<% end %>
</ul>  
  
  </div>
</nav>

rails/app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<%= render 'layouts/navigation' %>
<br>
<br>
<%= render 'layouts/messages' %>
    <%= yield %>

  </body>
</html>